### ISSUE TITLE
Issue using get_email_campaign function

### ISSUE THREAD

**Issue by chunyiyeo** [sendinblue/APIv3-python-library#15]
When using the get_email_campaign function, the following exception is raised if my campaign does not have input in "scheduled_at". This input is optional during campaign creation.

Exception when calling EmailCampaignsApi->get_email_campaign: (0)#012Reason: Failed to parse `` as datetime object

The api actually returns fine, it is the python client that raises the exception.

**Comment by aakanksha-sib** [comment]
Hi @chunyiyeo , This issue no longer exists. Apologies for the delayed response.
Thanks!
