### ISSUE TITLE
async is a reserved keyword in python 3.7

### ISSUE THREAD

**Issue by parth115** [sendinblue/APIv3-python-library#20]
account_api.py
line 119
async = params.get('async') does not work as async is now a reserved keyword in python starting from 3.7

**Comment by 2af** [comment]
Dear SIB, any update planned on it?

**Comment by aakanksha-sib** [comment]
We are currently supporting python upto version 3.5 . We will soon update our python wrapper to support version 3.7 .

**Comment by frossigneux** [comment]
Any update on this?
I am using python 3.7 and have this problem too.

**Comment by aakanksha-sib** [comment]
Hi @frossigneux ,
Thanks for sharing the PR. We will check if things get fixed and will get back to you.

**Comment by 2af** [comment]
frossigneux,
Ended up working with proper and stable MChimp.
Nothing personal, SIB, you are just outdated in our case.

**Comment by nwarchitect** [comment]
Is there any update? Python 3.7 was release on June 27, 2018. That's 18+months and we still have no compatibility.

Is there any roadmap available for this problem?
