### ISSUE TITLE
Support ODT as attachment

### ISSUE THREAD

**Issue by lolobosse** [sendinblue/APIv3-python-library#22]
Hey there, 

We use your API for 1 year now and it's quite frustrating to compress the `ODT` to `zip` before sending them.

Can you change that behaviour as well as the doc?

> Possible extension values = gif, png, bmp, cgm, jpg, jpeg, tif, tiff, rtf, txt, css, shtml, html, htm, csv, zip, pdf, xml, doc, docx, ics, xls, xlsx, ppt, tar, and ez.

**Comment by aakanksha-sib** [comment]
Hi @lolobosse , The support for `ODT` is now available.
Thanks!
