### ISSUE TITLE
get_attribute() returns type error

### ISSUE THREAD

**Issue by QuillyT** [sendinblue/APIv3-python-library#27]
I'm getting an error when I call [get_attributes()](https://github.com/sendinblue/APIv3-python-library/blob/master/docs/ContactsApi.md#get_attributes)

It's raising this error:
```
ValueError: Invalid value for `type` (boolean), must be one of ['text', 'date', 'float', 'id']
```

Looks like boolean should be added to the allowed_types list.

**Comment by aakanksha-sib** [comment]
Hi @QuillyT , We are on it. Will update you once fixed.

Thanks!

**Comment by aakanksha-sib** [comment]
Hi @QuillyT ,
This issue is fixed in the latest version.

Thanks!
