### ISSUE TITLE
get_email_campaign returning only recipients and statistics

### ISSUE THREAD

**Issue by maximilienGilet** [sendinblue/APIv3-python-library#34]
Using your sdk the get_email_campaign function returns only the recipients and statistics. This doesn't match the definition of your API reference 
https://developers.sendinblue.com/v3.0/reference#getemailcampaign

How to get the full informations for an email campaign ?

**Comment by aakanksha-sib** [comment]
Hi @maximilienGilet ,
Thanks for reaching out. We have identified the issue and we are already looking into the same.

We will shortly update you on the same.


Thanks,
Aakanksha
Sendinblue

**Comment by aakanksha-sib** [comment]
Hi @maximilienGilet ,
The issue has been fixed. Please move to v6.0.0

Thanks!
