### ISSUE TITLE
Create pypi package

### ISSUE THREAD

**Issue by brendanator** [sendinblue/APIv3-python-library#37]

**Comment by Lawouach** [comment]
Hi, could we have an ETA on a package on pypi? Right now, packaging this library is tedious and quite broken. We are debating if we need to use switch to a different service due to this problem :(

Cheers

**Comment by jcerjak** [comment]
Package is on pypi: https://pypi.org/project/sib-api-v3-sdk/ , so I guess this issue can be closed.
