### ISSUE TITLE
Time Limit Errors - no server response?

### ISSUE THREAD

**Issue by QuillyT** [sendinblue/APIv3-python-library#38]
This is an intermittent issue that has popped up pretty frequently for us.

When we are adding our users to SendInBlue, we use `create_contact()` and so far we haven't seen an instance where it fails to add the contact. However, we have noticed instances of the request timing out and us not getting a response from the SendInBlue server within 20 seconds.

We have not seen this for any other calls, but `create_contact()` is by far the most frequently called function.

When testing the API directly from the command-line, the time it has taken to receive a response has always been under 5 seconds, usually way less.

Has anyone else experienced this?
SendInBlue, have you guys seen this before?

Data from the start of the month with the number of incidents that we've seen per day:
- May 1: 4
- May 2: 6
- May 3: 6
- May 4: 2
- May 5: 3
- May 6: 2
- May 7: 5
- May 8: 0
- May 9: 0
- May 10: 2
- May 11: 2
- May 12: 1
- May 13: 4
- May 14: 2
- May 15: 6
- May 16: 3

(Note: this does not correlate with the number of users that we add per day.)

**Comment by Rudy080791** [comment]
Hi @QuillyT 

Thank you for reporting this issue. However, I would request you to please report this issue with our support team from your account , https://account.sendinblue.com/support as it might require further investigation and we will look into it.

Thanks!
