### ISSUE TITLE
Not compatible with Python3.7 - async is a keyword

### ISSUE THREAD

**Issue by h** [sendinblue/APIv3-python-library#40]
Please regenerate the library using Swagger. It is currently not compatible with python3.7 since "async" is now a keyword. This has been fixed in a recent release of Swagger: https://github.com/swagger-api/swagger-codegen/pull/8401

With Python3.7, you get the following error message when importing this library:

```
 Traceback (most recent call last):
  File "./env/lib/python3.7/site-packages/sib_api_v3_sdk/api/account_api.py", line 119
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

**Comment by Lawouach** [comment]
Hi all,

Any ETA on this one? This makes this library unusable :/

**Comment by erdimeola** [comment]
Hi, any plans on fixing this issue?

**Comment by Lawouach** [comment]
I think they don't really care

https://github.com/sendinblue/APIv3-python-library/issues/20#issuecomment-454762362

Best bet, call their API directly with requests or http3.

**Comment by aakanksha-sib** [comment]
Hi All,
The issue has been resolved.
Please use latest version 6.1.0

Thanks!
Sendinblue team
