### ISSUE TITLE
Error when sending only bcc emails

### ISSUE THREAD

**Issue by Esequiel378** [sendinblue/APIv3-python-library#48]
send_smtp_email = sib_api_v3_sdk.SendSmtpEmail(
                bcc                   = self.send_to,
                html_content    = self.content,
                sender              = self.sender,
                subject             = self.subject,
                params             = self.params
) # SendSmtpEmail | Values to send a transactional email

when i try to senf a transactional email with only bbc recipients, the api throw me this error

"Uncaught exception: Invalid value for `to`, must not be `None`"

**Comment by Rudy080791** [comment]
Hi @Esequiel378
This is the expected behaviour and you should pass the recipients in `To` field as well. Only then the same email will be sent to the recipients mentioned in `BCC` list.

Thanks
