### ISSUE TITLE
module 'sib_api_v3_sdk' has no attribute 'SMTPApi'

### ISSUE THREAD

**Issue by Alexnavi44** [sendinblue/APIv3-python-library#58]
Hello,

I receive this error when trying to send an email in python via sendinblue, and i can't find anything to solve this problem

**Comment by jcerjak** [comment]
@Alexnavi44 looks like `SMTPApi` was changed to `TransactionalEmailsApi` in the latest version (7.0.0).

Btw., is there a changelog anywhere for this Python library? There is general changelog for the API https://developers.sendinblue.com/changelog , but would be very useful to have a client specific changelog (with security fixes, breaking/non-breaking changes etc.).

**Comment by swarnim-sib** [comment]
Hi @jcerjak 

The changelog that you're referring to, is related to the Sendinblue API changelog.

To find a client-specific changelog, please refer to the specific client's `releases` section in Github itself.
Here is the Python SDK changelog: https://github.com/sendinblue/APIv3-python-library/releases

Hope the doubt is clear now.

Thanks!

**Comment by PiotrCzapla** [comment]
not really, the changelog does not show breaking changes explicit, so you force your customers to read every release notes, that isnt something i would expect from a business. it makes my life and others using your library harder just because you don't want to put the breaking changes highlighted properly.

**Comment by Rudy080791** [comment]
Hi @PiotrCzapla 
Sorry for the inconvenience caused. We understand your concern and will take care of such issues and implications in future.
Thanks!

**Comment by btoro** [comment]
@ruudy-sib Why are the docs still outdated on your website? None of the documents mention using `TransactionalEmailsApi` rather than `SMTPApi` ?
