### ISSUE TITLE
How to get an update_profile url, given a Contact

### ISSUE THREAD

**Issue by tlrh314** [sendinblue/APIv3-python-library#61]
The Sendinblue Campaigns allow adding an Update Profile form, e.g. to the footer of an email. This seems to generate a long hash url that allows that a recipient to change their preferences on a Sendinblue-hosted form. I would like to generate such a url via the Sendinblue API - is that possible given the form id and email address of the contact?

**Comment by Rudy080791** [comment]
Hi @tlrh314 
Currently, update profile tag is not supported via API. But we can add unsubscribe tag in footer parameter via API and it will redirect to default un-subscription page.
Please raise a support ticket in case you need further details.

Thanks
