### ISSUE TITLE
Library is not published on PyPI

### ISSUE THREAD

**Issue by egor83** [sendinblue/APIv3-python-library#62]
Can you please start publishing on PyPI again?

We are using pipenv, and trying to install requirements from Github leads to an error, and it appears that pipenv does not support installation from Github directly:
"[I reported this](https://stackoverflow.com/questions/50316275/how-to-use-pipenv-to-install-package-from-github) to pipenv and spaCy. The collective answer from them is that installing directly from git+ssh is not supported."

**Comment by Rudy080791** [comment]
Hi @egor83 

We are already publishing the wrappers on PyPi. The latest version was released on 22nd Jan, 2021 and can be found [here](https://pypi.org/project/sib-api-v3-sdk/).

Thanks

**Comment by egor83** [comment]
Thanks a lot! Again, as a wish - maybe add this data to README?

**Comment by Rudy080791** [comment]
Yes, we will definitely try and add it soon!

Thanks for the suggestion, again :)
