### ISSUE TITLE
Code sample does not work.

### ISSUE THREAD

**Issue by egor83** [sendinblue/APIv3-python-library#63]
I installed SendinBlue client and tried to run the sample provided in the README. Got an error:

`
Exception when calling AccountApi->get_account: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 31 Jan 2021 17:25:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '50', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d8bd6a1e3d10aabfda45690ac41f6c4621612113950; expires=Tue, 02-Mar-21 17:25:50 GMT; path=/; domain=.sendinblue.com; HttpOnly; SameSite=Lax; Secure', 'CF-Ray': '61a5225ca9c07b1b-DME', 'Access-Control-Allow-Origin': '*', 'CF-Cache-Status': 'BYPASS', 'access-control-allow-credentials': 'true', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'PUT, POST, GET, DELETE, PATCH, OPTIONS', 'cf-apo-via': 'origin,host', 'cf-request-id': '07fb13cdef00007b1bd7350000000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'sib-request-id': '18b07ba8-b8c5-97bc-b7f1-fc60515b3d20', 'X-Content-Type-Options': 'nosniff', 'x-envoy-upstream-service-time': '0', 'X-Sib-Server': 'SENDINBLUE-srv-pr-rancher-worker-10', 'X-XSS-Protection': '1', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare'})
HTTP response body: {"message":"Key not found","code":"unauthorized"}
`

Tried to create another API key, got the same error message.

PS Tried uncommenting Bearer prefix, did not help.

PPS Tried sample with raw curl, got the following:
`
{"code":"permission_denied","message":"Unable to send email. Your SMTP account is not yet activated. Please contact us at contact@sendinblue.com to request activation."}
`
Sent email request.

**Comment by Rudy080791** [comment]
Hi @egor83 

You will need to contact the support team for getting this activated.
Since the issue is not related to the wrapper, hence closing it.

Thanks

**Comment by egor83** [comment]
Thanks for response! We contacted the support team already - but just as a wish, a more detailed error message for Python library could be useful.

**Comment by Rudy080791** [comment]
Thanks for the suggestion, we will try to accommodate this request.

Also, you can find the latest code samples in our reference docs [here](https://developers.sendinblue.com/reference).
You can select the language tab as Python for the respective sample code.

Hope this helps!

Thanks
