### ISSUE TITLE
I can't send parameters in SendEmail () function

### ISSUE THREAD

**Issue by NeftaliAcosta** [sendinblue/APIv3-python-library#64]
I am trying to send transactional emails in Python through the client and using the sendEmail () method. Everything works, however, my template has parameters and I want to send them from the client, but they appear blank.
What am I doing wrong? 

`# create an instance of the API class
api_instance = sib_api_v3_sdk.TransactionalEmailsApi(sib_api_v3_sdk.ApiClient(configuration))
template_id = 196 # int | Id of the template

send_email = sib_api_v3_sdk.SendEmail(
	email_to = ["hola@jxxaocay.mx"],
	attributes = {
        "params.prospecto": "Carlos",
        "asesor": "Neftali Xaxaxaxa",
        "telefono": "22xxxx37090"
    }
	)

try:
    # Send a template
    api_response = api_instance.send_template(template_id, send_email)
    pprint(api_response)
except ApiException as e:
	print("Exception when calling TransactionalEmailsApi->send_template: %s\n" % e)
`

thank you.

**Comment by cyzanfar** [comment]
How are you calling them in your template? for any non-contact params, it seems that you need to call them in your template via `{{ params. asesor }}`.

**Comment by Rudy080791** [comment]
Hi @NeftaliAcosta 
Could you please try to use our latest method for sending transactional emails? It can be found [here](https://developers.sendinblue.com/reference/transactional-emails) in our reference docs and you can select the `Python` tab in the code example. 
Please refer to the screenshot below:
![PythonExample](https://user-images.githubusercontent.com/59564050/119350738-4f49a780-bcbd-11eb-8787-a2e6b71579f2.png)

Please let us know if you still face any issue.

Thanks

**Comment by ljmartinez1994** [comment]
{
  "result": {
    "params": {
      "name": "ljmartinez",
      "code": "3f3047ea-b8f6-45d3-9ed4-5e7834f9371e",
      "email": "luisothegreat@gmail.com"
    }
  },
  "statusCode": 200,
  "customStatusCode": 0
}

my api response is this, i am putting params.code and nothing

**Comment by ulises-castro** [comment]
@ljmartinez1994, you should modify your template 

changing your %code% to {{ params.code }} into your template.

It sucks how this docs were made, it not pretty much clear about this BREAKING CHANGES...
