### ISSUE TITLE
Preview Text in Email Campaign

### ISSUE THREAD

**Issue by yaldashbz** [sendinblue/APIv3-python-library#66]
how can I send "preview text" on creating an email campaign?

**Comment by Rudy080791** [comment]
Hi @yaldashbz 
Could you please explain what do you mean by "preview text" in context of API.

We provide textContent and htmlContent as mentioned [here](https://developers.sendinblue.com/reference/email-campaigns-1#createemailcampaign-1) in our reference.

Thanks

**Comment by Innsai** [comment]
In the API Reference (https://api.brevo.com/v3/emailCampaigns) when creating the Email Campaign you can send in the body of the request a property called previewText (Preview text or preheader of the email campaign). There is no such property in the definition of CreateEmailCampaign.
