### ISSUE TITLE
Bug found when using sendinblue apis

### ISSUE THREAD

**Issue by gaoxingliang** [sendinblue/APIv3-python-library#67]
Hi guys, I'm trying to migrate from api v2 to api v3.
and in production env, I found a lot of buggy cases and the api returned bug responses when accessing about campaigns.
We integrated with sib and use a lot of it as a base layer of our service.

**Case 1:**

some campaign not exists by using api: get_campaign_by_id. 
but they are actually exists. both java and python sdk return None.

**Case2:**
some campaign can't update name by neither api nor sendinblue UI

**Case3:**
When I tried to update the campaign name I got 403 forbiddon error (only for some campaign). but I can update by UI

**case4:**
When I tried to update the campaign name I got method not allowed (only for some campaign). but I can update by UI
 method not allowed

**case5:**
update the campaign name and got error- internal server error (even retry)

All those cases can be reproduced by using our account and some special campaign.
I don't know what's happening. Help wanted. If need more reproduce process, please contact my company email : egao@freshlime.com

**Comment by Rudy080791** [comment]
Hi @gaoxingliang 
Could you please raise a support ticket for these issues so that our team can look into it and provide all the relevant details?

Thanks
